### ISSUE TITLE
Extracting PFS stuck at 0%

### ISSUE THREAD

**Issue by Brutal-sam** [ultimaweapon/obliteration#1]
![Screenshot 2022-09-29 174323](https://user-images.githubusercontent.com/94696121/193112720-1650aecf-0d7d-43c6-84eb-0bcecda9fbc6.png)

**Comment by Brutal-sam** [comment]
@ultimaweapon where does the emulator save the settings? I want to change the directory where games are installed but I can't get this window to show up again so I can change the location, how do I change the location?
![vlcsnap-2022-09-29-19h25m33s112](https://user-images.githubusercontent.com/94696121/193113132-2dbe5efb-05e4-4f49-a1ce-e1e385d0129e.png)

**Comment by ultimaweapon** [comment]
The PKG installation not yet fully functional (actually I just finished it about 5 minutes ago but I need to test it first). Currently there is no UI to edit location to install games so you need to update it manually. On Windows it will stored in Windows Registry at `HKEY_CURRENT_USER\Software\Obliteration\Obliteration`. Just delete that path and run Obliteration again.

**Comment by Brutal-sam** [comment]
now the new build extracts the full game and solves the issue, but I think apps/games can't run yet?
![Screenshot 2022-09-30 130800](https://user-images.githubusercontent.com/94696121/193266689-e8804d54-8716-44cd-95f9-db15c6493fab.jpg)

**Comment by ultimaweapon** [comment]
Right. It cannot run any app/game yet. It may take a coupled of months for me to make it able to run a simple game that Kyty already able to run. So let's hope I got more people to help on develop this :)
