### ISSUE TITLE
Try Zlib instead of DEFLATE when de-compression PFCS

### ISSUE THREAD

**Issue by ultimaweapon** [ultimaweapon/obliteration#18]
I guess the actual algorithm is Zlib, not DEFLATE because the current code need to skip the first 2 bytes, which I suspect it is Zlib header.

**Comment by Mou-Ikkai** [comment]
Looking into it, it does seem to use zlib for compression and decompression.

**Comment by ultimaweapon** [comment]
Try replace `Decompress` with https://docs.rs/flate2/1.0.24/flate2/read/struct.ZlibDecoder.html.
