### ISSUE TITLE
Fix implementation of RSA from_components to support Result.

### ISSUE THREAD

**Issue by Mou-Ikkai** [ultimaweapon/obliteration#42]
In order to be able to upgrade to RSA 0.7, we need to be able to handle the fallible error for primes. The PR that caused this addition is here: https://github.com/RustCrypto/RSA/pull/167

**Comment by ultimaweapon** [comment]
In our case the returned `Result` can be ignored with [unwrap](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap) because the supplied value is hard-coded, which is a valid value.

**Comment by Mou-Ikkai** [comment]
> In our case the returned `Result` can be ignored with [unwrap](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap) because the supplied value is hard-coded, which is a valid value.

Fixed! :3
