### ISSUE TITLE
Cannot create reader for system image.

### ISSUE THREAD

**Issue by Mou-Ikkai** [ultimaweapon/obliteration#44]
Failed to install (D:\852\PS4UPDATE1.PUP.dec) to (D:\systemfolder): Cannot create reader for system image -> cannot read root directory -> unknown entry on #1 on cluster #5 (critical memory 1)

This error occurs when attempting to install decrypted firmware version 8.52

**Comment by ultimaweapon** [comment]
I forgot to remove the code that invokes an incomplete exFAT implementation. Will fix it tonight or you can fix it by removing these lines https://github.com/ultimaweapon/obliteration/blob/main/src/pup/src/lib.rs#L105-L109

**Comment by ultimaweapon** [comment]
https://github.com/ultimaweapon/obliteration/commit/a97789e6a99fe57a5c76dfa5091d1724abc36c10
