### ISSUE TITLE
Github Self-Hosted Runner (Windows)

### ISSUE THREAD

**Issue by Mou-Ikkai** [ultimaweapon/obliteration#45]
I currently have a computer in the attic that is unused (Besides from being a Pi-Hole), it has a Ryzen 5 2600, 16gb of ram, and a 2tb SSD. I might set it up to be a self-hosted runner for quicker compilations of Windows builds. 
According to github, their specs for default runners is:
```
2-core CPU (x86_64)
7 GB of RAM
14 GB of SSD space
```
While the server I have has:
```
6-core CPU (12 threads x86_64)
16 GB of RAM
2 TB of SSD space
```

**Comment by Mou-Ikkai** [comment]
I will, however, need your help unless if I become admin, as I need to get an access key .w.

**Comment by ultimaweapon** [comment]
We can't do that due to transparency problem. With self-hosted runner the users will not know if the binaries they got come from the code without modifications.

For chatting platform I'll setup IRC so everyone can join easily.

**Comment by ultimaweapon** [comment]
Just added the information how to join IRC to README but I will offline for the rest of December due to personal things.
