### ISSUE TITLE
entry_4096: The system cannot find the file specified (os error 2).

### ISSUE THREAD

**Issue by AussiePlick** [ultimaweapon/obliteration#47]
When the .exe boots, and tries to load games, the following error appears.
entry_4096: The system cannot find the file specified (os error 2).

**Comment by Mou-Ikkai** [comment]
Hi there! I'll assign @ultimaweapon to this as I believe he is currently in the middle of implementing OS Firmware usage.

**Comment by Mou-Ikkai** [comment]
Uh, correction. Seems like a possibly corrupted package file. As entry_4096 is a Param.SFO reader.

**Comment by ultimaweapon** [comment]
Looks like it was tried to load the game that was installed with old Obliteration. Re-install all of your games should fix the problem.

**Comment by AussiePlick** [comment]
Problem was it was showing error because I was trying to load extracted .PKG games and not PKG. So all good now. cheers

**Comment by ultimaweapon** [comment]
Thanks for the update. The problem has been resolved so I will close the issue.
