### ISSUE TITLE
Design application icon

### ISSUE THREAD

**Issue by ultimaweapon** [ultimaweapon/obliteration#5]
This one I cannot create by myself so I'll appreciate if someone can help me with this :)

**Comment by Mou-Ikkai** [comment]
> This one I cannot create by myself so I'll appreciate if someone can help me with this :)

What are you looking for in the icon design?

**Comment by ultimaweapon** [comment]
Just an icon for Obliteration that will be display in the Obliteration executable and in the Window title.

**Comment by Mou-Ikkai** [comment]
> Just an icon for Obliteration that will be display in the Obliteration executable and in the Window title.
![o-icon](https://user-images.githubusercontent.com/45863583/194097431-f712e174-46ad-4bc0-ad45-4f65e3539a3d.png)
How about this? An obliterated O with the color of Rust :P

**Comment by ultimaweapon** [comment]
This is awesome! Could you create a PR? We need at least `.png` files with 512 x 512 pixel.

**Comment by Mou-Ikkai** [comment]
> This is awesome! Could you create a PR? We need at least `.png` files with 512 x 512 pixel.

Indeed it is 512x512! Tell me where to put it and I will! I even have an ico file directly from the art program.
